#include "Color.hpp"


#include <cmath>
#include <vector>
#include <algorithm>


int iterator = 0;
constexpr int maximum = 50;


double Color::f(const double t) const {
  double t3 = t*t*t;
  return (t3 > 0.008856)? t3 : (t-16.0/116.0)/7.787;
}


double Color::gamma(const double u) const {
  return (u <= 0.0031308)? 12.92*u : 1.055*pow(u, 1.0/2.4)-0.055;
}


/**
 * Mostly generated by ChatGPT and use "as is".
 */
void Color::generate(const double h, const double c, const double l) {
  // HCL -> LAB
  double hr = h*M_PI/180.0;
  double a = std::cos(hr)*c;
  double b = std::sin(hr)*c;
  // LAB -> XYZ
  double y = (l+16.0)/116.0;
  double x = a/500.0+y;
  double z = y-b/200.0;

  x = ( 95.047*f(x))/100.0;
  y = (100.000*f(y))/100.0;
  z = (108.883*f(z))/100.0;

  double r =  3.2406*x -1.5372*y -0.4986*z;
  double g = -0.9689*x +1.8758*y +0.0415*z;
  double b2 = 0.0557*x -0.2040*y +1.0570*z;

  red = std::clamp(gamma(r), 0.0, 1.0);
  green = std::clamp(gamma(g), 0.0, 1.0);
  blue = std::clamp(gamma(b2), 0.0, 1.0);
  alpha = 1.0;
}


Color::Color() {
  generate(360.0*iterator/maximum, 60.0, 65.0);
  iterator = (iterator+1)%maximum;
}


Color::Color(double red, double green, double blue, double alpha): red(red), blue(blue), green(green), alpha(alpha) {}


Color::~Color() {}
